import com.example.drools.model.*;
global com.example.drools.model.global.Result result;

dialect "mvel"

rule "Regra Nome"
    when
        RuleObject(data['name'] == "Kelvin")
    then
        System.out.println("The name is Kelvin");
        result.getRulesExecuted().add("Rule001");
end

rule "Regra Idade"
    when
        RuleObject(data['age'] > 25)
    then
        System.out.println("The age is greater than 25");
        result.getRulesExecuted().add("Rule002");
end